### ISSUE TITLE
finish-args-not-defined error with finish-args:[]

### ISSUE THREAD

**Issue by sigmaSd** [flathub/flatpak-builder-lint#212]
Using `finish-args:[]` used to work , but recently this lint started to happen `finish-args-not-defined`.

Maybe this is correct and expected, but I'm just opening the issue because the behavior has changed.

The fix/workaround now is to to populate finish-args with something even if its not needed.

**Comment by bbhtt** [comment]
You need an exception like this:

https://github.com/flathub/flatpak-builder-lint/blob/655d3fbeb53f11dcd54472851aec70472fc19451/flatpak_builder_lint/staticfiles/exceptions.json#L1179

Regular apps are assumed to always have a finish-arg.

**Comment by sigmaSd** [comment]
I see thanks

**Comment by bbhtt** [comment]
> I see thanks

Please make a PR against that file, following the example.

**Comment by hfiguiere** [comment]
The test was written for checking the manifest but lately linter has been checking the generated metadata which changes things a bit.

**Comment by bbhtt** [comment]
I added a fix for this for baseapps and extensions since those two can never have finish-args.

https://github.com/flathub/flatpak-builder-lint/pull/211/commits/400cdb64b5045c545eea81b58bdd4f4962ca8837

The same cannot be said for console applications because they may or may not have them.

Eg. https://github.com/flathub/dev.paullee.scraterpreter.Scrapec/blob/master/dev.paullee.scraterpreter.Scrapec.json has `type=console-application` but comes with finish-args
